- src/main/java/com/draconist/goodluckynews/domain/member/converter/MemberConverter.java
- src/main/java/com/draconist/goodluckynews/domain/member/dto/JoinDTO.java
- src/main/java/com/draconist/goodluckynews/domain/member/dto/MemberInfoDTO.java
- src/main/java/com/draconist/goodluckynews/domain/member/entity/Member.java
- src/main/java/com/draconist/goodluckynews/domain/member/service/MemberService.java
> ex) #10
Member객체에서
keywords를 string으로 받도록 수정했습니다.
article에서만 영향이 가는 부분이기 때문에 이 부분은 현재 개발에 있어 크게 신경쓰지 않아도 될 것 같습니다
> #10 회원정보 keyword 수정

- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/ErrorStatus.java
> fix: 에러 코드 수정

- src/main/java/com/draconist/goodluckynews/global/config/WebConfig.java
> ex) #17
전역 cors 설정
webconfig만 추가됨
> #17: CORS 전역 설정

- src/main/java/com/draconist/goodluckynews/domain/article/controller/ArticleController.java
- src/main/java/com/draconist/goodluckynews/domain/article/repository/ArticleRepository.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
> ex) #9
기사 랜덤으로 1개반환하기
프론트 추가 요청
> #9 feat/기사 랜던으로 보여주기

- src/main/java/com/draconist/goodluckynews/domain/article/controller/ArticleController.java
- src/main/java/com/draconist/goodluckynews/domain/article/dto/ArticleDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/dto/ArticleListDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/dto/ArticleLongContentDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/dto/ArticleZipListDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/entity/ArticleEntity.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
> ex) #9
originalDate 기사 원 시간 반환합니다
> #9: fix/originalDate추가

- src/main/java/com/draconist/goodluckynews/domain/member/converter/MemberConverter.java
- src/main/java/com/draconist/goodluckynews/domain/member/dto/MemberInfoDTO.java
> fix: 회원 정보 이메일 포함

- src/main/java/com/draconist/goodluckynews/domain/article/controller/NewsScraper.java
> fix: 이미지 상대경로 문제 #9

- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
> fix:completed 수정

- src/main/java/com/draconist/goodluckynews/domain/article/dto/ArticleZipListDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/CompletedTimeService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/ErrorStatus.java
> #9 : !hotfix 상세조회 null exception

- src/main/java/com/draconist/goodluckynews/domain/article/service/CompletedTimeService.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
> ex) #9
!hotfix: null exception
> !hotfix: null exception #9

- src/main/java/com/draconist/goodluckynews/domain/article/repository/HeartRepository.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/CompletedTimeService.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
#9
bookmark boolean값 builder 수정
> #9 fix: bookmarked boolean값 제대로

- src/main/java/com/draconist/goodluckynews/GoodluckynewsApplication.java
- src/main/java/com/draconist/goodluckynews/domain/article/controller/EveryDayArticleCrawler.java
- src/main/java/com/draconist/goodluckynews/domain/article/repository/ArticleRepository.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
> fix: 랜덤 기사 반환 키워드 기반으로 변경

- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
> ex) #9 
이전 pull request 가 씹힌 것 같아 다시 보냅니다.
1) 00시 정각에 크롤링하는 기능 추가
2) 북마크 처음 생성시 bookmarked = true로 생성하도록 HeartService 변경했씁니다.
> pull request re

- src/main/java/com/draconist/goodluckynews/domain/article/entity/Heart.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/HeartService.java
> 북마크 초깃값 false문제 해결

- src/main/java/com/draconist/goodluckynews/domain/article/repository/HeartRepository.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
bookmark 모아보기
#9 
북마크 모아보기가 북마크 여부와 관계없이 뜨는 오류 가 있었습니다.
useId와 북마크 여부 모두를 검사하는 repository를 작성하여 service 모델을 수정했습니다.
> fix: bookmark 모아보기

- src/main/java/com/draconist/goodluckynews/domain/place/dto/PlaceDTO.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
#42 
dto에 플레이스 아이디 추가하였고 서비스 코드 수정했습니다
> Fix: place id 추가 

- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/CommentService.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/ErrorStatus.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/SuccessStatus.java
#44 
희소식, 댓글 에러 성공 핸들러 추가하였고 서비스에도 적용시켰습니다
> fix: 희소식, 댓글 에러 성공 핸들러 추가

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
> Fix: 검색 누락 수정 

- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/PostDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/PostLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> fix: 좋아요 및 댓글 수 포함

- src/main/java/com/draconist/goodluckynews/domain/place/dto/PlaceDTO.java
- src/main/java/com/draconist/goodluckynews/domain/place/entity/PlaceLike.java
- src/main/java/com/draconist/goodluckynews/domain/place/repository/PlaceLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
> Fix: 플레이스 좋아요 수 추가 

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/PostDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/entity/Post.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/PostLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/PostRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/CommentService.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
- src/main/java/com/draconist/goodluckynews/domain/place/controller/PlaceController.java
- src/main/java/com/draconist/goodluckynews/domain/place/repository/PlaceLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/place/repository/PlaceRepository.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/SuccessStatus.java
#51 
-희소식, 댓글 삭제 기능 추가 
- 내가 댓글을 작성한 희소식 데이터로 수정 
- 희소식 생성 타이틀 제거 및  Multipart/form-data로 전환
> fix: 희소식, 플레이스, 댓글 에러 수정 및 삭제 기능 추가

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/goodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> fix:희 소식 생성

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> fix: 희소식 생성 수정

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
> fix :희소식 생성

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> ex) 희소식 생성 수정
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> fix: 희소식 생성

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/CommentController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/CommentDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/entity/Comment.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/entity/Post.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/CommentService.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/SuccessStatus.java
알람 & title, comment의 userid 받아오기
> 알람 & title, comment의 userid 받아오기

- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/CommentRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/CommentService.java
> fix: 대댓글 알림 중복 수정

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/PostDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/entity/Post.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/PostRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> fix: 희소식 모아보기 플레이스명 추가

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/PostController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/repository/PostRepository.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
> feature: 플레이스별 희소식 조회

- src/main/java/com/draconist/goodluckynews/domain/goodNews/controller/CommentController.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/CommentService.java
> fix: 답글 단 소식 모아보기 플레이스명 추가

- src/main/java/com/draconist/goodluckynews/domain/goodNews/dto/GoodnewsDto.java
- src/main/java/com/draconist/goodluckynews/domain/goodNews/service/PostService.java
> fix: content not null 속성 추가

- src/main/java/com/draconist/goodluckynews/domain/place/controller/PlaceController.java
- src/main/java/com/draconist/goodluckynews/domain/place/dto/PlaceDTO.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
-북마크 정보 추가
API 응답에서 isBookmark 값을 받을 수 있음.
전체 조회 (findAllWithPagination)에서 isBookmark 포함
사용자가 북마크한 플레이스인지 여부를 확인할 수 있음.
내가 만든 플레이스 조회 (getMyPlaces)에도 isBookmark 포함
북마크 여부를 UI에 반영할 수 있음.
> fix: 플레이스 북마크 수정 

- src/main/java/com/draconist/goodluckynews/domain/article/controller/ArticleController.java
- src/main/java/com/draconist/goodluckynews/domain/article/controller/EveryDayArticleCrawler.java
- src/main/java/com/draconist/goodluckynews/domain/article/repository/ArticleRepository.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/ArticleService.java
> ex) #9
메인 화면에 들어갔을때 오늘 최신 뉴스를 랜덤으로 볼 수 있어야 했습니다.
오전 3시에 크롤링을 진행하도록 수정하였고, 오늘자의 기사를 랜덤으로 보여주도록 만들었습니다.
> feat: 오전 3시 크롤링& 오늘자 기사 가져오기

- src/main/java/com/draconist/goodluckynews/domain/place/controller/PlaceController.java
- src/main/java/com/draconist/goodluckynews/domain/place/dto/PlaceCreateDTO.java
- src/main/java/com/draconist/goodluckynews/domain/place/dto/PlacePageResponse.java
- src/main/java/com/draconist/goodluckynews/domain/place/repository/PlaceLikeRepository.java
- src/main/java/com/draconist/goodluckynews/domain/place/repository/PlaceRepository.java
- src/main/java/com/draconist/goodluckynews/domain/place/service/PlaceService.java
- src/main/java/com/draconist/goodluckynews/global/enums/statuscode/ErrorStatus.java
- src/main/java/com/draconist/goodluckynews/global/exception/ExceptionAdvice.java
#76
플레이스(커뮤니티) 생성하기
플레이스(커뮤니티) 전체 조회하기
특정 플레이스 가져오기\
플레이스(커뮤니티) 삭제하기
플레이스 수정하기
플레이스 북마크
"플레이스 별 희소식 외" 작업 완료
거 브랜치명은 급해서ㅋㅋㅋㅋ 미안하다
> #76 fix place관련 모든 오류 및 리팩토링

- src/main/java/com/draconist/goodluckynews/domain/article/dto/SevenCompletedGraphDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/CompletedTimeService.java
#9
그래프에서 시작 시간, 종료 시간 반환하도록 수정하였습니다.
> feat: #9 시작 시간 종료 시간 반환

- src/main/java/com/draconist/goodluckynews/domain/article/controller/ArticleController.java
- src/main/java/com/draconist/goodluckynews/domain/article/dto/FirstCreatedAndTodayDto.java
- src/main/java/com/draconist/goodluckynews/domain/article/service/CompletedTimeService.java
> fix: #9 response entity형태

- src/main/java/com/draconist/goodluckynews/domain/member/dto/WriterInfoDto.java
> #98 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> refactor : 직렬화 누락 추가
